global:
  scrape_interval: 10s
  evaluation_interval: 5s

rule_files:

alerting:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
